.TH 
.SH NOM
mythread_mutex_lock \-\- Verrouille un mutex
.SH SYNOPSYS
#include <mythread.h>

int 
mythread_mutex_lock (mythread_mutex_t *mutex)

.SH DESCRIPTION
La fonction 
.B mythread_mutex_lock 
verrouille  
.I mutex
. Si le mutex est déjà verrouillé, le thread appelant est mis en attente de son déverrouillage.

.SH VALEURS DE RETOUR
Si le verrouillage réussit
.B mythread_mutex_lock
renvoie 0. Sinon la fonction renvoie le code d'erreur.

.SH ERREURS
.B mythread_mutex_lock
va retourner les erreurs:
.TP
.B [EINVAL]
.I le mutex passé en argument n'est pas valide

.SH VOIR AUSSI
.BR "mythread_mutex_init" "(3)," "mythread_mutex_unlock" "(3)" 
