.TH 
.SH NOM
mythread_create \-\- Crée un nouveau thread
.SH SYNOPSYS
#include <mythread.h>

int
mythread_create (mythread_t *thread, const mythread_attr_t *attr, 
    void *(*func)(void *), void *args)

.SH DESCRIPTION
La fonction 
.B mythread_create 
crée un nouveau thread. Si elle s'exécute avec succès, mythread_create va stocker le nouveau thread là où pointe 
.I thread.
Quand le thread sera exécuté, la routine 
.I func 
sera appelée.

.SH VALEURS DE RETOUR
Si il n'y a aucun problème, 
.B mythread_create
retourne 0. Dans le cas contraire, le numéro de l'erreur est retourné.

.SH ERREURS
.B mythread_create
va retourner les erreurs:
.TP
.B [ENOMEM]
.I il n'y a pas assez de mémoire pour créer un nouveau thread


.SH VOIR AUSSI
.BR "mythread_init" "(3)," "mythread_join" "(3)," "mythread_exit" "(3)" 
