.TH 
.SH NOM
mythread_self \-\- Retourne le descripteur du thread appelant
.SH SYNOPSYS
#include <mythread.h>

mythread_t
mythread_self (void)

.SH DESCRIPTION 
La fonction 
.B mythread_self 
retourne le descripteur de thread du thread appelant.

.SH VALEURS DE RETOUR
La fonction 
.B mythread_self 
retourne le descripteur de thread du thread appelant.

.SH ERREURS
Pas d'erreur possible.

.SH VOIR AUSSI
.BR "mythread_create" "(3)"
